# Topics Covered:
# Pandas
 Pandas is a powerful Python library for data manipulation and analysis. It provides easy-to-use data structures and data analysis tools for working with structured data.
## Installation:
pip install pandas
## Importing Pandas:
import pandas as pd


## Real-Life Problems Pandas Solves:
### Problem 1: Working with Large Data Files
Without Pandas:
- Opening a CSV file with 10,000 rows in Excel = slow and crashes
- Hard to process thousands of records

With Pandas:
- Can easily handle millions of rows
- Fast and efficient
- Process data in seconds
### Problem 2: Data Cleaning
Without Pandas:
- You have student data with missing marks
- Manually finding and filling empty cells in Excel = tedious
- Removing duplicate entries one by one = time-consuming

With Pandas:
- Find all missing values in one line
- Fill or remove them automatically
- Remove duplicates instantly
### Problem 3: Data Analysis
Without Pandas:
- Calculate average marks of 1000 students manually
- Find who scored highest in each subject
- Group students by city and calculate stats

With Pandas:
- Calculate average, max, min in one line
- Group and analyze data easily
- Get insights quickly
### Problem 4: Reading Different File Types
Without Pandas:
- Different code to read CSV, Excel, JSON
- Complex parsing required
- Error-prone

With Pandas:
- Read CSV: pd.read_csv('file.csv')
- Read Excel: pd.read_excel('file.xlsx')
- Read JSON: pd.read_json('file.json')
- Simple and easy

In [2]:
import pandas as pd
import numpy as np

# DataFrame:
 A DataFrame is like a COMPLETE TABLE in Excel with multiple columns.
- Complete table
- Multiple columns
- Most commonly used
- Each column is a Series
## use:
 1. Store Complete Datasets
 2. Data Analysis and Exploration
    (Analyze relationships between different columns)
 3. Read and Write Files
    (Load data from CSV, Excel, JSON files)

In [26]:
df=pd.DataFrame(np.arange(10,20),index=[f'row{i}' for i in range(10)],columns=['col1']) # create dataframe
df.head()  # head() prints first five records

      col1
row0    10
row1    11
row2    12
row3    13
row4    14

In [60]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['col1','col2','col3','col4'])

In [28]:
df.head()

      col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [29]:
# convert it to excel sheet
df.to_csv('test.csv') # you can see it in your directory as test.csv

# accesing the elements
## 1) .loc 2) .iloc 3) using column name

In [31]:
# check the type
type(df.loc['Row2'])

pandas.core.series.Series

In [32]:
df.loc['Row2']

col1    4
col2    5
col3    6
col4    7
Name: Row2, dtype: int64

In [99]:
# using column name 
df['col3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: col3, dtype: int64

In [102]:
# multiple column 
df[['col1','col2']]

      col1  col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

In [33]:
# using iloc
df.iloc[0:2,0:2]

      col1  col2
Row1     0     1
Row2     4     5

In [36]:
#check type 
type(df.iloc[0:3,0:4])

pandas.core.frame.DataFrame

In [37]:
df.iloc[:,:]

      col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [38]:
df.iloc[0:2,0]

Row1    0
Row2    4
Name: col1, dtype: int64

In [39]:
df.iloc[0,0:4]

col1    0
col2    1
col3    2
col4    3
Name: Row1, dtype: int64

In [40]:
df.iloc[1:3,1:3]

      col2  col3
Row2     5     6
Row3     9    10

In [57]:
# convert datframe to array 
# it will just remove index , columns and column indexex 
# .values is used to convert datframe to array
# to covert numpy used .to_numpy
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
df.iloc[:,:].values.shape

(5, 4)

In [48]:
df.iloc[:,:].values.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
df.iloc[:,:].to_numpy

<bound method DataFrame.to_numpy of       col1  col2  col3  col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19>

In [85]:
df2=pd.DataFrame([[1,2,3,4,5],[6,1,2,3,4],[5,5,6,3,4],[6,1,2,3,4]],index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4','c5'])
df2.head()

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   1   2   3   4
r3   5   5   6   3   4
r4   6   1   2   3   4

In [86]:
# some inbuilt method
#isnull() 
df2.isnull()

       c1     c2     c3     c4     c5
r1  False  False  False  False  False
r2  False  False  False  False  False
r3  False  False  False  False  False
r4  False  False  False  False  False

In [95]:
df2.isnull().sum()  # output show col1 has o null values col2 also same and so on

c1    0
c2    0
c3    0
c4    0
c5    0
dtype: int64

In [96]:
# check unique values 
# 1) using value_count()
df2.value_counts() # it counts unique row

c1  c2  c3  c4  c5
6   1   2   3   4     2
1   2   3   4   5     1
5   5   6   3   4     1
Name: count, dtype: int64

In [97]:
df2['c3'].value_counts # This counts how many times each unique value appears in the col3 column.

<bound method IndexOpsMixin.value_counts of r1    3
r2    2
r3    6
r4    2
Name: c3, dtype: int64>

In [92]:
# count()
# Counts non-null (non-NaN) values
df2.count()

c1    4
c2    4
c3    4
c4    4
c5    4
dtype: int64

In [93]:
# nunique()
#Counts number of unique values
df2.nunique()

c1    3
c2    3
c3    3
c4    2
c5    2
dtype: int64

In [94]:
df2['c5'].nunique()

2

In [6]:
# reading CSV file

In [7]:
df = pd.read_csv('test.csv')

In [8]:
df.head() # print first five record

  Unnamed: 0  col1  col2  col3  col4
0       Row1     0     1     2     3
1       Row2     4     5     6     7
2       Row3     8     9    10    11
3       Row4    12    13    14    15
4       Row5    16    17    18    19

In [9]:
df.info() # metadata of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      object
 1   col1        5 non-null      int64
 2   col2        5 non-null      int64
 3   col3        5 non-null      int64
 4   col4        5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [11]:
df.describe() # it describe the statistics such as mean,standard deviation........ of dataset numeric column it ignore categorial data(non-numeric)

            col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [14]:
# get unique categeory count from dataset column
df['col1'].value_counts()

col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [15]:
df.isnull().sum()

Unnamed: 0    0
col1          0
col2          0
col3          0
col4          0
dtype: int64

In [16]:
# read from specific columns in dataset 
# use "usecols" parameter of read_cvs

df=pd.read_csv('test.csv',usecols=['col1','col4'])

In [18]:
df

   col1  col4
0     0     3
1     4     7
2     8    11
3    12    15
4    16    19

In [20]:
# to convert dataframe into dataset
# use to_csv()
df.to_csv('test2')

# StringIO
  StringIO converts a string → file-like object
  or we can say makes string behave like file.

In [33]:
from io import StringIO

data=('a,b,c,d\n'
           '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11,12')

In [34]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [35]:
df=pd.read_csv(StringIO(data))

In [36]:
df.head()

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [40]:
# dtype parameter of read_csv 
#It controls the data type of columns while reading the CSV.
df=pd.read_csv(StringIO(data),dtype=float)

In [41]:
df

     a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [48]:
df=pd.read_csv(StringIO(data),dtype=int)

In [43]:
df

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [50]:
df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':object})

In [51]:
df

   a     b   c   d
0  1   2.0   3   4
1  5   6.0   7   8
2  9  10.0  11  12

In [52]:
df.dtypes

a      int64
b    float64
c     object
d      int64
dtype: object

In [53]:
df

   a     b   c   d
0  1   2.0   3   4
1  5   6.0   7   8
2  9  10.0  11  12

In [57]:
# index_col parameter of read_csv()
# making any column to index of dataset
# syntax : index_col="column_index"
#for ex consider above dataset

pd.read_csv(StringIO(data),index_col=2) # here column 2 means c will become index

    a   b   d
c
3   1   2   4
7   5   6   8
11  9  10  12