# Read Json to csv with pandas
 JSON is just a way to represent data in text form using:
- Key–value pairs
- Easy to read & write
- Used in almost every API and application

In [1]:
import pandas as pd

In [9]:
data='[{"name":"Dnyanesh","age":25},{"name":"yash","age":27}]'

In [10]:
pd.read_json(data)

C:\Users\DNYANESHWAR\AppData\Local\Temp\ipykernel_3812\1661395064.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data)

       name  age
0  Dnyanesh   25
1      yash   27

In [34]:
from io import StringIO

In [16]:
df=pd.read_json(StringIO(data))

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df.head()

       name  age
0  Dnyanesh   25
1      yash   27

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

# nested json

In [12]:
data='''[{"name":"dnyanesh","age":25,"marks":{"math":89,"bio":69}},
                  {"name":"yadnyanesh","age":28,"marks":{"math":80,"bio":99}}]'''

In [7]:
df=pd.read_json(StringIO(data))

In [8]:
df

         name  age                    marks
0    dnyanesh   25  {'math': 89, 'bio': 69}
1  yadnyanesh   28  {'math': 80, 'bio': 99}

In [3]:
url = "https://jsonplaceholder.typicode.com/users" #we can obtained data from external sources
df = pd.read_json(url)   #we loaded the data into Pandas

In [4]:
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
# convert json to csv
df.to_csv('fake.csv')

In [7]:
# convert jason to deffirent json format using read_json() <oreient='  '> parameter
df.to_json(orient="records")

'[{"id":1,"name":"Leanne Graham","username":"Bret","email":"Sincere@april.biz","address":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"phone":"1-770-736-8031 x56442","website":"hildegard.org","company":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"}},{"id":2,"name":"Ervin Howell","username":"Antonette","email":"Shanna@melissa.tv","address":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"phone":"010-692-6593 x09125","website":"anastasia.net","company":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"}},{"id":3,"name":"Clementine Bauch","username":"Samantha","email":"Nathan@yesenia.net","address":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"phone":"1-463-123-4447","website":"ramiro.info","company":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"}},{"id":4,"name":"Patricia Lebsack","username":"Karianne","email":"Julianne.OConner@kory.org","address":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"phone":"493-170-9623 x156","website":"kale.biz","company":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"}},{"id":5,"name":"Chelsey Dietrich","username":"Kamren","email":"Lucio_Hettinger@annie.ca","address":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"phone":"(254)954-1289","website":"demarco.info","company":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"}},{"id":6,"name":"Mrs. Dennis Schulist","username":"Leopoldo_Corkery","email":"Karley_Dach@jasper.info","address":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"phone":"1-477-935-8478 x6430","website":"ola.org","company":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"}},{"id":7,"name":"Kurtis Weissnat","username":"Elwyn.Skiles","email":"Telly.Hoeger@billy.biz","address":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"phone":"210.067.6132","website":"elvis.io","company":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"}},{"id":8,"name":"Nicholas Runolfsdottir V","username":"Maxime_Nienow","email":"Sherwood@rosamond.me","address":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"phone":"586.493.6943 x140","website":"jacynthe.com","company":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"}},{"id":9,"name":"Glenna Reichert","username":"Delphine","email":"Chaim_McDermott@dana.io","address":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"phone":"(775)976-6794 x41206","website":"conrad.com","company":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"}},{"id":10,"name":"Clementina DuBuque","username":"Moriah.Stanton","email":"Rey.Padberg@karina.biz","address":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}},"phone":"024-648-3804","website":"ambrose.net","company":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}]'

In [8]:
df.to_json(orient="split")

'{"columns":["id","name","username","email","address","phone","website","company"],"index":[0,1,2,3,4,5,6,7,8,9],"data":[[1,"Leanne Graham","Bret","Sincere@april.biz",{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"1-770-736-8031 x56442","hildegard.org",{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"}],[2,"Ervin Howell","Antonette","Shanna@melissa.tv",{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"010-692-6593 x09125","anastasia.net",{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"}],[3,"Clementine Bauch","Samantha","Nathan@yesenia.net",{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"1-463-123-4447","ramiro.info",{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"}],[4,"Patricia Lebsack","Karianne","Julianne.OConner@kory.org",{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"493-170-9623 x156","kale.biz",{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"}],[5,"Chelsey Dietrich","Kamren","Lucio_Hettinger@annie.ca",{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"(254)954-1289","demarco.info",{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"}],[6,"Mrs. Dennis Schulist","Leopoldo_Corkery","Karley_Dach@jasper.info",{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"1-477-935-8478 x6430","ola.org",{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"}],[7,"Kurtis Weissnat","Elwyn.Skiles","Telly.Hoeger@billy.biz",{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"210.067.6132","elvis.io",{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"}],[8,"Nicholas Runolfsdottir V","Maxime_Nienow","Sherwood@rosamond.me",{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"586.493.6943 x140","jacynthe.com",{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"}],[9,"Glenna Reichert","Delphine","Chaim_McDermott@dana.io",{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"(775)976-6794 x41206","conrad.com",{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"}],[10,"Clementina DuBuque","Moriah.Stanton","Rey.Padberg@karina.biz",{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}},"024-648-3804","ambrose.net",{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}]]}'

# Reading HTML content
 In Pandas, HTML tables can be directly extracted from web pages using the function:
 - pd.read_html()
 - Reads tables from HTML pages (like websites or HTML files).
 - Automatically finds <table> tags and converts them into DataFrames.

In [2]:
url = "https://www.w3schools.com/html/html_tables.asp"

In [6]:
dfs = pd.read_html(url)

In [7]:
type(dfs)

list

In [5]:
dfs[0] # table one

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [10]:
dfs[1]  # table two

          Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table

# Reading EXcel content

In [17]:
dfex=pd.read_excel('management mcq.xlsx')

In [18]:
dfex.head()

,q_id,q_description,a,b,c,d,ans,q_level
0,514,Indian factory act come in to force on ----------,1st May 1960,1st April 1949,15th August 1947,26th January 1950,1st April 1949,R
1,515,"As per Indian factory act, The person who has ...",Employee,worker,occupier,None of the above,occupier,R
2,516,Section 27 under the Industrial dispute act is...,Manufacturing process,Penalty for instigation,occupier,None of the above,Penalty for instigation,R
3,517,"As per Indian Factory act, Employer has to pro...",50,100,200,250,250,R
4,518,NaN,Section 7,Section 27,Section 5,None of the above,Section 27,R

# Pickling 
  Pickling is the process of converting a Python object into a byte stream (binary format) so it can be saved to a file or transferred.
## Why Pickling is Used
- Save trained machine learning models
- Store complex data (lists, dictionaries, DataFrames)
- Transfer data between programs

- Pickling → object → byte stream
- Unpickling → byte stream → object

In [22]:
# let convert above file to pickle
dfex.to_pickle('testpickle')

In [23]:
df=pd.read_pickle('testpickle')

In [24]:
df.head()

,q_id,q_description,a,b,c,d,ans,q_level
0,514,Indian factory act come in to force on ----------,1st May 1960,1st April 1949,15th August 1947,26th January 1950,1st April 1949,R
1,515,"As per Indian factory act, The person who has ...",Employee,worker,occupier,None of the above,occupier,R
2,516,Section 27 under the Industrial dispute act is...,Manufacturing process,Penalty for instigation,occupier,None of the above,Penalty for instigation,R
3,517,"As per Indian Factory act, Employer has to pro...",50,100,200,250,250,R
4,518,NaN,Section 7,Section 27,Section 5,None of the above,Section 27,R